### PR TITLE
Gfw adapter

### PR DESCRIPTION
**Pull request by solomon-negusse**
Adding GFW connector (https://github.com/resource-watch/adapter-gfw/pull/1)

### CODE REVIEW

**Review by tiagojsag — CHANGES_REQUESTED** [review]
Overall looks pretty much on point. The only suggestion I have is around naming - I think having /gfw routes, or a MS folder called "gfw-proxy" may be ambiguous and cause confusion - /gfw can mean a lot of things, and "proxy" is already the name of another (poorly named) PREP related MS. My suggestion is to use "gfw-adapter" for everything, but I'll leave this up to you to decide on if and what to change.

Also: please add this MS to the MS spreadsheet, along with the k8s service port, so we keep track of this sort of thing.

**Comment by solomon-negusse** [comment]
Thanks @tiagojsag. I have updated the name in places of potential conflict (such as lb target groups, folder) as suggested. I have kept /gfw in routes with the expectation that there should be one gfw connector. This may also change to something else sometime in the future as GFW Data API is starting to host non-forest related datasets.

**Comment by tiagojsag** [comment]
LGTM. Did you run a "terraform plan" to validate your changes?

**Comment by solomon-negusse** [comment]
**Ignore this**

Yes, `terraform plan` is succeeding now but for some reason adding the new [key pair ](https://github.com/resource-watch/api-infrastructure/pull/103/commits/9c1522d4d199652716973897e373f1050c694270) didn't result in the bastion host being recreated with new authorized_keys file that includes my ssh pub key. 
`data.template_file.bastion_setup` gets updated so I'm thinking that should have triggered an update of the instance as it has new `user_data` from the rendered template.

**Comment by solomon-negusse** [comment]
@tiagojsag There is a life cycle [condition](https://github.com/resource-watch/api-infrastructure/blob/production/terraform/modules/vpc/main.tf#L215) in the bastion instance config preventing its recreation to add my ssh key so please advise on whether I should remove that condition or someone add my ssh keys manually for me.

**Comment by tiagojsag** [comment]
I'll add your key

**Comment by solomon-negusse** [comment]
Thanks @tiagojsag. Please let me know when you have done so.

**Comment by tiagojsag** [comment]
key added to the 3 bastion hosts

**Comment by solomon-negusse** [comment]
@tiagojsag: ran `terraform plan` against `staging` environment as suggested and verified changes. The plan shows that new resources (api gateway, kubernetes service, etc) will be created for GFW connector and API gateway will be redeployed. So this is ready to deploy pending approval of this PR.

**Review by tiagojsag — APPROVED** [review]

**Pull request merged**
