### PR TITLE
Downgrade eks instance types

### PR DESCRIPTION
**Pull request by ethanroday**
- Downgrade EKS instance types from `m5a.xlarge` to `r5a.large` for the following node groups (other node groups excluded based on CPU usage or the fact that they've already been optimized):
  - `apps-node-group`
  - `webapps-node-group`
  - `gfw-node-group`
  - `core-node-group`
- Comment out time-based node group scaling logic for now. This may need to be reintroduced at a later time.

### CODE REVIEW

**Review by thomas-maschler — COMMENTED** [review]
So you don't make use of the autoscaling anymore?
I would put the instance type in the `terraform-dev.tfvar` file

**Comment by ethanroday** [comment]
Correct. Based on CPU analysis and discussion last week, we decided we'd just try the downgrade and monitor to see if any of the daily jobs fail.
Any particular reason this should go in `terraform-dev.tfvar`? The point is that this gets merged across all three environments.

**Comment by thomas-maschler** [comment]
ok, you would have the option to have different sized instance for the different environments ( I assume that traffic in staging and dev is much much lower)

**Review by thomas-maschler — APPROVED** [review]

**Comment by ethanroday** [comment]
Ah, I see what you mean. Current plan is to have the same instance type across environments just fewer instances in dev and staging.

**Pull request merged**
