### PR TITLE
Add deletion endpoints to api gateway config

### PR DESCRIPTION
**Pull request by tiagojsag**

### CODE REVIEW

**Review by solomon-negusse — COMMENTED** [review]
LGTM. Do we need to add these endpoints to localstack's tf as well?

**Comment by tiagojsag** [comment]
> LGTM. Do we need to add these endpoints to localstack's tf as well?

no, LS uses the same code changed here

**Comment by tiagojsag** [comment]
> LGTM. Do we need to add these endpoints to localstack's tf as well?

no, LS uses the same code changed here

**Comment by tiagojsag** [comment]
> LGTM. Do we need to add these endpoints to localstack's tf as well?

no, LS uses the same code changed here

**Review by solomon-negusse — APPROVED** [review]

**Pull request merged**
