### PR TITLE
Add CT mongo backups

### PR DESCRIPTION
**Pull request by tiagojsag**

### CODE REVIEW

**Comment by tiagojsag** [comment]
the actual backup script is best reviewed by comparing it with the preexisting one, and looking at the diff.

**Comment by hotzevzl** [comment]
looks good to me too.

as a later update, would it help to keep one single copy of the mongo backup shell script and invoke it with instance-specific args from `cronjobs.sh`? Of course modifying the `mongobackup.sh` script itself to set internal variables from CLI args. Since we have full control over the invocation, there shouldn't :roll_eyes: be much of a concern about args validation (as long as this is clearly signposted).

but likely not so much of a gain in terms of avoided duplication given the specific context and scale :smiley:

**Comment by tiagojsag** [comment]
I completely agree with you, and normally that's what I would do. However, since there's a big infrastructure already set up, no backups for this particular database, and we are not super confident in many things, I took the "dumb but safe" approach. It's not DRY at all, but if it works, I can dry it up later, with extra confidence that the dumb solution worked, and we now have backups from which to recover in case something goes horribly wrong

**Comment by hotzevzl** [comment]
yep, totally agree! it's also nice to start a weekend with that good feeling of knowing that data is being backed up :tada:

**Pull request merged**
